In [1]:
import pandas as pd
import json
import requests

from config import api_key

In [2]:
file = ("nba_acronym.csv")
data = pd.read_csv(file)
#print(data)
df = pd.DataFrame(data)
df
stadium_list = df['team'].tolist()
stadium_name = []
stadium_state = []
stadium_lat = []
stadium_lng = []

In [3]:
for stadium_search in stadium_list:
    
    params = {"address": stadium_search,
              "key": api_key
              }

    base_url = "https://maps.googleapis.com/maps/api/geocode/json"

    

    st_geo = requests.get(base_url, params).json()

    lat = st_geo["results"][0]["geometry"]["location"]["lat"]
    lng = st_geo["results"][0]["geometry"]["location"]["lng"]


    # Use lat, lng to use places API to find nearest dentist
    target_search = "stadium"

    params = {
        "location": f"{lat},{lng}",
        "types": target_search,
        "rankby": "distance",
        "key": api_key
    }

    base_url = f"https://maps.googleapis.com/maps/api/geocode/json?latlng={lat},{lng}&key={api_key}"


    # Run request
    st_reverse_geo = requests.get(base_url).json()

    
    

    st = st_reverse_geo["results"][0]["formatted_address"]
    stadium_state.append(st)
    
    
    
    lt =  st_geo["results"][0]["geometry"]["location"]["lat"]
    stadium_lat.append(lt)
    
    ln =  st_geo["results"][0]["geometry"]["location"]["lng"]
    stadium_lng.append(ln)
    
    #print(json.dumps(st_reverse_geo))
    #print(ln)
results = list(zip(stadium_list, stadium_state, stadium_lat, stadium_lng))
results_df = pd.DataFrame(results)
results_df  = results_df.rename(columns={results_df.columns[0]: "team name", \
                                      results_df.columns[1]: "address", \
                                     results_df.columns[2]: "latitude", \
                                        results_df.columns[3]: "longitude"})

#results_df["address"] = results_df.str.split(",", n = 1, expand = True)
#results_df['new', 'new1'] = pd.DataFrame(results_df.address.str.split(',',1).tolist(),
                                   #columns = ['address','city'])
#results_df
#print(stadium_state)
address_df = pd.DataFrame(stadium_state)
street_df = pd.DataFrame(results_df['address'].str.split(',').values.tolist())


full_results_df = pd.concat([results_df, street_df], axis=1, sort=False)
full_results_df = full_results_df.rename(columns={full_results_df.columns[4]: "street", \
                                      full_results_df.columns[5]: "city", \
                                     full_results_df.columns[6]: "zip"})
full_results_df = full_results_df[['team name', 'street', 'city', 'zip', 'latitude', 'longitude']]
full_results_df

,team name,street,city,zip,latitude,longitude
0,Atlanta Hawks,1968 Hawks Lane,Atlanta,GA 30329,33.826990,-84.335791
1,Brooklyn Nets,274 36th St,Brooklyn,NY 11232,40.655476,-74.011762
2,Boston Celtics,226 Causeway St,Boston,MA 02114,42.366730,-71.059387
3,Charlotte Hornets,333 E Trade St,Charlotte,NC 28202,35.225137,-80.839344
4,Chicago Bulls,1901 W Madison St,Chicago,IL 60612,41.880660,-87.674066
5,Cleveland Cavaliers,1 Center Ct,Cleveland,OH 44115,41.497157,-81.687943
6,Dallas Mavericks,2500 Victory Ave,Dallas,TX 75219,32.790492,-96.810285
7,Denver Nuggets,1000 Chopper Cir,Denver,CO 80204,39.749190,-105.007651
8,Detroit Pistons,76 Henry St,Detroit,MI 48201,42.341028,-83.055038
9,Golden State Warriors,1001 Broadway,Oakland,CA 94607,37.802326,-122.273756
10,Houston Rockets,1510 Polk St,Houston,TX 77002,29.750769,-95.362103
11,Indiana Pacers,132 W Walnut St,Indianapolis,IN 46204,39.777162,-86.160960
12,Los Angeles Clippers,6951 S Centinela Ave,Los Angeles,CA 90094,33.983276,-118.399384
13,Los Angeles Lakers,2275 E Mariposa Ave,El Segundo,CA 90245,33.924532,-118.383985
14,Memphis Grizzlies,191 Beale St,Memphis,TN 38103,35.138055,-90.051107
15,Miami Heat,601 Biscayne Blvd,Miami,FL 33132,25.781958,-80.187855
16,Milwaukee Bucks,1543 N 2nd St,Milwaukee,WI 53212,43.050697,-87.913621
17,Minnesota Timberwolves,600 N 1st Ave,Minneapolis,MN 55403,44.979528,-93.275989
18,New Orleans Pelicans,1501 Dave Dixon Dr,New Orleans,LA 70113,29.949035,-90.082057
19,New York Knicks,Pennsylvania Station,4 Pennsylvania Plaza,New York,40.750504,-73.993439
20,Oklahoma City Thunder,100 W Reno Ave,Oklahoma City,OK 73102,35.463431,-97.515094
21,Orlando Magic,8701 Maitland Summit Blvd,Orlando,FL 32810,28.635564,-81.399876
22,Philadelphia 76ers,3601 S Broad St,Philadelphia,PA 19148,39.901267,-75.171976
23,Phoenix Suns,US Airways Center,201 E Jefferson St,Phoenix,33.445875,-112.071856
24,Portland Trail Blazers,1 N Center Ct St,Portland,OR 97227,45.531926,-122.666860
25,Sacramento Kings,500 David J Stern Walk,Sacramento,CA 95814,38.580280,-121.498581
26,San Antonio Spurs,1 AT&T Center Parkway,San Antonio,TX 78219,29.427147,-98.437487
27,Toronto Raptors,40 Bay St,Toronto,ON M5J 2X2,43.643293,-79.378326
28,Utah Jazz,301 S Temple,Salt Lake City,UT 84101,40.768223,-111.901278
29,Washington Wizards,601 F St NW,Washington,DC 20004,38.898109,-77.020991

In [5]:
#team acronym dataframe
team_acro_df = pd.DataFrame(df['team acronym'])

#combining team_acro_df with full_results_df
full_team_df = pd.concat([team_acro_df, full_results_df], axis=1, sort=False)

#full_team_df.reset_index(drop=True)
#full_team_df.set_index('team acronym')
full_team_df

,team acronym,team name,street,city,zip,latitude,longitude
0,ATL,Atlanta Hawks,1968 Hawks Lane,Atlanta,GA 30329,33.826990,-84.335791
1,BKN,Brooklyn Nets,274 36th St,Brooklyn,NY 11232,40.655476,-74.011762
2,BOS,Boston Celtics,226 Causeway St,Boston,MA 02114,42.366730,-71.059387
3,CHA,Charlotte Hornets,333 E Trade St,Charlotte,NC 28202,35.225137,-80.839344
4,CHI,Chicago Bulls,1901 W Madison St,Chicago,IL 60612,41.880660,-87.674066
5,CLE,Cleveland Cavaliers,1 Center Ct,Cleveland,OH 44115,41.497157,-81.687943
6,DAL,Dallas Mavericks,2500 Victory Ave,Dallas,TX 75219,32.790492,-96.810285
7,DEN,Denver Nuggets,1000 Chopper Cir,Denver,CO 80204,39.749190,-105.007651
8,DET,Detroit Pistons,76 Henry St,Detroit,MI 48201,42.341028,-83.055038
9,GSW,Golden State Warriors,1001 Broadway,Oakland,CA 94607,37.802326,-122.273756
10,HOU,Houston Rockets,1510 Polk St,Houston,TX 77002,29.750769,-95.362103
11,IND,Indiana Pacers,132 W Walnut St,Indianapolis,IN 46204,39.777162,-86.160960
12,LAC,Los Angeles Clippers,6951 S Centinela Ave,Los Angeles,CA 90094,33.983276,-118.399384
13,LAL,Los Angeles Lakers,2275 E Mariposa Ave,El Segundo,CA 90245,33.924532,-118.383985
14,MEM,Memphis Grizzlies,191 Beale St,Memphis,TN 38103,35.138055,-90.051107
15,MIA,Miami Heat,601 Biscayne Blvd,Miami,FL 33132,25.781958,-80.187855
16,MIL,Milwaukee Bucks,1543 N 2nd St,Milwaukee,WI 53212,43.050697,-87.913621
17,MIN,Minnesota Timberwolves,600 N 1st Ave,Minneapolis,MN 55403,44.979528,-93.275989
18,NOP,New Orleans Pelicans,1501 Dave Dixon Dr,New Orleans,LA 70113,29.949035,-90.082057
19,NYK,New York Knicks,Pennsylvania Station,4 Pennsylvania Plaza,New York,40.750504,-73.993439
20,OKC,Oklahoma City Thunder,100 W Reno Ave,Oklahoma City,OK 73102,35.463431,-97.515094
21,ORL,Orlando Magic,8701 Maitland Summit Blvd,Orlando,FL 32810,28.635564,-81.399876
22,PHI,Philadelphia 76ers,3601 S Broad St,Philadelphia,PA 19148,39.901267,-75.171976
23,PHX,Phoenix Suns,US Airways Center,201 E Jefferson St,Phoenix,33.445875,-112.071856
24,POR,Portland Trail Blazers,1 N Center Ct St,Portland,OR 97227,45.531926,-122.666860
25,SAC,Sacramento Kings,500 David J Stern Walk,Sacramento,CA 95814,38.580280,-121.498581
26,SAS,San Antonio Spurs,1 AT&T Center Parkway,San Antonio,TX 78219,29.427147,-98.437487
27,TOR,Toronto Raptors,40 Bay St,Toronto,ON M5J 2X2,43.643293,-79.378326
28,UTA,Utah Jazz,301 S Temple,Salt Lake City,UT 84101,40.768223,-111.901278
29,WAS,Washington Wizards,601 F St NW,Washington,DC 20004,38.898109,-77.020991

In [ ]:
engine = create_engine("mysql+pymysql://{user}:{pw}@localhost/{db}"
                       .format(user="root",
                               pw="S@roth6249",
                               db="season_stats_db"))
data.to_sql(con=engine, name='season_stats_table', if_exists='replace')