In [61]:
import pandas as pd

In [62]:
arena = pd.read_table('./Resources/arena.txt')

In [63]:
arena_df = pd.DataFrame(arena)

In [65]:

arena_df = arena_df.rename(columns={arena_df.columns[0]: "Data" })
arena_df = arena_df[arena_df['Data'].str.contains('-')]
arena_df = arena_df[~arena_df['Data'].str.contains('Location|Phone|Website|Email|Founded')]
arena_df  = pd.DataFrame(arena_df['Data'].str.split().values.tolist())
arena_df = arena_df.iloc[:,[0,1,2,3,4,5,6]]
#header_df  = pd.DataFrame(header_df['Data'].str.split().values.tolist())
#header_df  = header_df.rename(columns={header_df.columns[0]: "Status",
#                                     header_df.columns[1]: "Flow",
#                                     header_df.columns[2]: "Error",
#                                     header_df.columns[3]: "Warning"})
arena_df

,0,1,2,3,4,5,6
0,1949-51,Wheaton,Field,House,"Moline,",IL,"6,000"
1,1951-55,Milwaukee,Arena,"Milwaukee,",WI,"11,000",None
2,1955-68,Kiel,Auditorium,St.,"Louis,",MO,"10,000"
3,1968-72,Alexander,Memorial,Coliseum,"Atlanta,",GA,"7,166"
4,1972-97,Omni,Coliseum,"Atlanta,",GA,"6,378",None
5,1997-99,Georgia,Dome,"Atlanta,",GA,"21,570",None
6,1999-,Philips,Arena,"Atlanta,",GA,"20,000",None
7,1946-95,Boston,Garden,"Boston,",MA,"14,890",None
8,1995-05,Fleet,Center,"Boston,",MA,"18,624",None
9,2005-,TD,Garden,"Boston,",MA,"18,624",None
10,2004-,Time,Warner,Cable,Arena,"Charlotte,",NC
11,1966-67,Chicago,Amphitheater,"Chicago,",IL,"11,002",None
12,1967-94,Chicago,Stadium,"Chicago,",IL,"18,676",None
13,1994-,United,Center,"Chicago,",IL,"21,711",None
14,1970-74,Cleveland,Arena,"Cleveland,",OH,"11,000",None
15,1974-94,The,Coliseum,"Richfield,",OH,"20,273",None
16,1994-05,Gund,Arena,"Cleveland,",OH,"20,562",None
17,2005-,Quicken,Loans,Arean,"Cleveland,",OH,"20,562"
18,1980-01,Reunion,Arena,"Dallas,",TX,"18,042",None
19,01-,American,Airlines,Arena,"Dallas,",TX,"19,200"
20,1967-75,Auditorium,Arena,"Denver,",CO,"6,841",None
21,1975-99,McNichols,Sports,Arena,"Denver,",CO,"17,171"
22,1999-,Pepsi,Center,"Denver,",CO,"19,309",None
23,1948-52,North,Side,High,School,Gym,Fort
24,1952-57,Memorial,Coliseum,Fort,"Wayne,",IN,"9,306"
25,1957-61,Olympia,Stadium,"Detroit,",MI,"14,000",None
26,1961-78,Cobo,Arena,"Detroit,",MI,"11,147",None
27,1978-88,Silverdome,"Pontiac,",MI,"22,366",None,None
28,1988-,Palace,of,Auburn,Hills,Auburn,Hills
29,1946-52,Philadelphia,Arena,"Philadelphia,",PA,"7,777",None
...,...,...,...,...,...,...,...
105,2013-,Sleep,Train,Arena,"Sacramento,",CA,"17,317"
106,San,"Antonio,",TX,78203-1031,None,None,None
107,1967-70,Memorial,Auditorium,"Dallas,",TX,"8,088",None
108,1970-71,Moody,"Coliseum,","Dallas,",TX,"8,500",None
109,1971-73,Moody,Coliseum,"Dallas,",TX,"9,500",None
110,1973-93,HemisFair,Arena,San,"Antonio,TX","16,057",None
111,1993-02,Alamodome,San,"Antonio,TX","25,557",None,None
112,2002-10,SBC,Center,San,"Antonio,TX","20,557",None
113,2010-,AT&T,Center,San,"Antonio,TX","18,418",None
114,1967-78,Seattle,Center,Coliseum,"Seattle,",WA,"14,098"
115,1978-85,Kingdome,"Seattle,",WA,"40,192",None,None
116,1985-94,Seattle,Center,Coliseum,"Seattle,",WA,"14,252"
117,1994-95,Tacoma,Dome,"Tacoma,",WA,"19,000",None
118,1995-08,Key,Arena,"Seattle,",WA,"17,100",None
119,2008-,Chesapeake,Energy,Arena,"Oklahoma,",OK,"18,203"
120,1995-99,SkyDome,"Toronto,",ON,"22,911",None,None
121,1999-,Air,Canada,Centre,"Toronto,",ON,"19,500"
122,1974-75,Municipal,Auditorium,New,Orleans,"55,675",None
123,1975-79,Superdome,New,Orleans,None,None,None
124,1979-91,Salt,Palace,Salt,Lake,City,"14,000?"
125,1991-06,Delta,Center,Salt,Lake,City,"19,911"
126,2006-15,Energy,Solutions,Arena,Salt,Lake,City
127,2015-,Vivint,Smart,Home,Arena,Salt,Lake
128,1961-62,Chicago,Amphitheater,"Chicago,",IL,"11,000",None
129,1962-63,Chicago,Coliseum,"Chicago,",IL,"7,100",None
130,1963-73,Baltimore,Civic,Center,"Baltimore,",MD,"12,289"
131,1973-97,USAir,Arena,"Landover,",MD,"18,756",None
132,1997-05,MCI,Center,"Washington,",DC,"21,500",None
133,2005-,Verizon,Center,Washington,DC,"20,356",None
134,Ste.,200,"Seattle,",WA,98109-9711,None,None