In [25]:
import pandas as pd
import json
import requests

from config import api_key

In [26]:
file = ("test_csv.csv")
data = pd.read_csv(file)
#print(data)
df = pd.DataFrame(data)
df
stadium_list = df['arenas'].tolist()
stadium_name = []
stadium_state = []
stadium_lat = []
stadium_lng = []

In [36]:
for stadium_search in stadium_list:
    
    #stadium_search = "name"


    params = {
        "address": stadium_search,
        "key": api_key
    }

    base_url = "https://maps.googleapis.com/maps/api/geocode/json"

    

    st_geo = requests.get(base_url, params).json()

    lat = st_geo["results"][0]["geometry"]["location"]["lat"]
    lng = st_geo["results"][0]["geometry"]["location"]["lng"]


    # Use lat, lng to use places API to find nearest dentist
    target_search = "stadium"

    params = {
        "location": f"{lat},{lng}",
        "types": target_search,
        "rankby": "distance",
        "key": api_key
    }

    base_url = f"https://maps.googleapis.com/maps/api/geocode/json?latlng={lat},{lng}&key={api_key}"


    # Run request
    st_reverse_geo = requests.get(base_url).json()

    
    

    st = st_reverse_geo["results"][0]["formatted_address"]
    stadium_state.append(st)
    
    
    
    lt =  st_geo["results"][0]["geometry"]["location"]["lat"]
    stadium_lat.append(lt)
    
    ln =  st_geo["results"][0]["geometry"]["location"]["lng"]
    stadium_lng.append(ln)
    
    #print(json.dumps(st_reverse_geo))
    #print(ln)
results = list(zip(stadium_list, stadium_state, stadium_lat, stadium_lng))
results_df = pd.DataFrame(results)
results_df  = results_df.rename(columns={results_df.columns[0]: "arena name", \
                                      results_df.columns[1]: "address", \
                                     results_df.columns[2]: "latitude", \
                                        results_df.columns[3]: "longitude"})

#results_df["address"] = results_df.str.split(",", n = 1, expand = True)
#results_df['new', 'new1'] = pd.DataFrame(results_df.address.str.split(',',1).tolist(),
                                   #columns = ['address','city'])
#results_df
#print(stadium_state)
address_df = pd.DataFrame(stadium_state)
street_df = pd.DataFrame(results_df['address'].str.split(',').values.tolist())


full_results_df = pd.concat([results_df, street_df], axis=1, sort=False)
full_results_df = full_results_df.rename(columns={full_results_df.columns[4]: "street", \
                                      full_results_df.columns[5]: "city", \
                                     full_results_df.columns[6]: "zip"})
full_results_df = full_results_df[['arena name', 'street', 'city', 'zip', 'latitude', 'longitude']]
full_results_df

,arena name,street,city,zip,latitude,longitude
0,American Airlines Arena,601 Biscayne Blvd,Miami,FL 33132,25.781401,-80.186969
1,American Airlines Center,2500 Victory Ave,Dallas,TX 75219,32.790506,-96.810355
2,Amway Center,400 W Church St,Orlando,FL 32801,28.539221,-81.383854
3,AT&T Center,1 AT&T Center Parkway,San Antonio,TX 78219,29.427147,-98.437487
4,Bankers Life Fieldhouse,Bankers Life Fieldhouse,125 E Georgia St,Indianapolis,39.763887,-86.155459

In [ ]:
engine = create_engine("mysql+pymysql://{user}:{pw}@localhost/{db}"
                       .format(user="root",
                               pw="S@roth6249",
                               db="season_stats_db"))
data.to_sql(con=engine, name='season_stats_table', if_exists='replace')

{'arena name': [], 'address': ['601 Biscayne Blvd, Miami, FL 33132, USA', '2500 Victory Ave, Dallas, TX 75219, USA', '400 W Church St, Orlando, FL 32801, USA', '1 AT&T Center Parkway, San Antonio, TX 78219, USA', 'Bankers Life Fieldhouse, 125 E Georgia St, Indianapolis, IN 46204, USA'], 'latitude': [25.7814014, 32.7905064, 28.5392214, 29.4271471, 39.7638867], 'longitude': [-80.18696899999999, -96.8103549, -81.3838535, -98.4374874, -86.1554587]}

{'arena name': 'stadium_name',
 'address': 'stadium_state',
 'latitude': 'stadium_lat',
 'longitude': 'stadium_lng'}